CREATE TABLE USERS
(
    FIRST_NAME VARCHAR(50),
    LAST_NAME VARCHAR(50),
    EMAIL VARCHAR(100),
    USERNAME VARCHAR(50) PRIMARY KEY NOT NULL,
    PASSWORD VARCHAR(20) 
);

CREATE TABLE POST
(
    POST_ID INTEGER(50) PRIMARY KEY NOT NULL,
    POST_NAME VARCHAR(50) UNIQUE NOT NULL,
    POST_BODY VARCHAR(200),
    USERNAME VARCHAR(50),
    FOREIGN KEY (USERNAME) REFERENCES USERS(USERNAME)
);

CREATE TABLE CREATION
(
    POSTDATE DATE,
    USERNAME VARCHAR(50),
    POSTID INTEGER(10),
    FOREIGN KEY (USERNAME) REFERENCES USERS(USERNAME),
    FOREIGN KEY (POSTID) REFERENCES POST(POST_ID)
);
